In [1]:
#Creating the emapthy and media data frame from ABCD data
#Variables of interest
#Demographics
#Screen time questionnaire
#Prosocial behaviors
#NIJ-SD Child Personality Disposition
#COVID Survey

In [2]:
#import libraries and tools
import pandas as pd
import os as os
import matplotlib.pyplot as plt
from functools import reduce

In [3]:
#set directory - this may need to be modified if pulling data from a differe director
os.chdir ('../')
os.chdir ('../')
os.chdir ('../')
os.chdir ('../')
os.chdir ('srv/lab/fmri/abcd/beh/')
os.getcwd()

'/srv/lab/fmri/abcd/beh'

In [4]:
#Read in variables of interest
demographics = pd.read_csv("abcd_lpds01.txt", delimiter='\t', na_values=[""], low_memory= False)
youth_screentime = pd.read_csv("abcd_stq01.txt", delimiter='\t', na_values=[""], low_memory= False)
parent_screentime = pd.read_csv("stq01.txt", delimiter='\t', na_values=[""], low_memory= False)
youth_prosocial = pd.read_csv("abcd_psb01.txt", delimiter='\t', na_values=[""], low_memory= False)
parent_prosocial = pd.read_csv("psb01.txt", delimiter='\t', na_values=[""], low_memory= False)

In [5]:
os.chdir ('ABCDSubStudies/')
os.getcwd()

'/srv/lab/fmri/abcd/beh/ABCDSubStudies'

In [6]:
youth_personality = pd.read_csv("abcd_socdev_child_pdis01.txt", delimiter='\t', na_values=[""], low_memory= False)
parent_personality = pd.read_csv("abcd_socdev_p_pdis01.txt", delimiter='\t', na_values=[""], low_memory= False)
#youth_covid = pd.read_csv("yabcdcovid19questionnaire01.txt", delimiter='\t', na_values=[""], low_memory= False)
parent_covid = pd.read_csv("pabcdcovid19questionnaire01.txt", delimiter='\t', na_values=[""], low_memory= False)

In [8]:
#Back to main directory
os.chdir ('../')
os.chdir ('../')
os.chdir ('../')
os.chdir ('../')
os.chdir ('../')
os.chdir ('srv/lab/fmri/abcd/beh/')
os.getcwd()

'/srv/lab/fmri/abcd/beh'

In [9]:
#Clean & Combine
#start with the most limiting dataset, NIJ
youth_personality = youth_personality.iloc[1: , :]
youth_personality.head(10)

,collection_id,abcd_socdev_child_pdis01_id,dataset_id,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,socialdev_cpd_001,...,socialdev_cpd_113,socialdev_cpd_114,socialdev_cpd_115,socialdev_cpd_116,socialdev_cpd_117,socialdev_cpd_118,socialdev_cpd_119,socialdev_cpd_120,socialdev_cpd_121,collection_title
1,2573,13427,47311,NDAR_INVYVVMMD41,NDAR_INVYVVMMD41,02/22/2020,142,F,sd_wave1_arm_3,3,...,1,1,0,0,0,1,0,0,1,Adolescent Brain Cognitive Development Study (...
2,2573,12586,47311,NDAR_INVJN2G8BWG,NDAR_INVJN2G8BWG,07/21/2019,143,M,sd_wave1_arm_3,2,...,1,0,0,0,1,0,0,0,0,Adolescent Brain Cognitive Development Study (...
3,2573,12589,47311,NDAR_INVJR23U8DW,NDAR_INVJR23U8DW,05/31/2019,128,F,sd_wave1_arm_3,2,...,1,0,0,0,1,1,0,0,1,Adolescent Brain Cognitive Development Study (...
4,2573,13430,47311,NDAR_INVYZ353ZBM,NDAR_INVYZ353ZBM,06/03/2019,129,F,sd_wave1_arm_3,1,...,1,1,0,0,0,1,0,0,0,Adolescent Brain Cognitive Development Study (...
5,2573,12687,47311,NDAR_INVLNA4879N,NDAR_INVLNA4879N,11/01/2019,126,M,sd_wave1_arm_3,2,...,0,0,0,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
6,2573,12701,47311,NDAR_INVLVT4DDY4,NDAR_INVLVT4DDY4,03/08/2019,120,M,sd_wave1_arm_3,2,...,2,1,1,1,1,1,0,1,0,Adolescent Brain Cognitive Development Study (...
7,2573,11926,47311,NDAR_INV99DBA2DJ,NDAR_INV99DBA2DJ,04/04/2019,144,F,sd_wave1_arm_3,3,...,2,1,0,1,2,2,0,0,0,Adolescent Brain Cognitive Development Study (...
8,2573,11933,47311,NDAR_INV9ANUKVD0,NDAR_INV9ANUKVD0,10/24/2019,153,M,sd_wave1_arm_3,2,...,1,0,0,1,1,0,0,1,1,Adolescent Brain Cognitive Development Study (...
9,2573,11953,47311,NDAR_INV9ZXTBCKF,NDAR_INV9ZXTBCKF,09/23/2020,145,F,sd_wave1_arm_3,2,...,1,0,0,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
10,2573,12802,47311,NDAR_INVN4F57516,NDAR_INVN4F57516,04/18/2019,123,F,sd_wave1_arm_3,2,...,1,0,0,0,0,0,0,2,0,Adolescent Brain Cognitive Development Study (...

In [10]:
youth_nij_empathy = youth_personality[["subjectkey", "src_subject_id", "interview_date", 
                                       "interview_age", "sex", "eventname", "socialdev_cpd_053_cads", "socialdev_cpd_052_cads", "socialdev_cpd_054_cads", 
                                       "socialdev_cpd_051_cads", "socialdev_cpd_057_icu", "socialdev_cpd_002", "socialdev_cpd_049",
                                       "socialdev_cpd_035", "socialdev_cpd_039", "socialdev_cpd_059_cads", "socialdev_cpd_060_cads",
                                       "socialdev_cpd_061_cads", "socialdev_cpd_062_icu"]]

In [11]:
youth_nij_empathy.head(10)

,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,socialdev_cpd_053_cads,socialdev_cpd_052_cads,socialdev_cpd_054_cads,socialdev_cpd_051_cads,socialdev_cpd_057_icu,socialdev_cpd_002,socialdev_cpd_049,socialdev_cpd_035,socialdev_cpd_039,socialdev_cpd_059_cads,socialdev_cpd_060_cads,socialdev_cpd_061_cads,socialdev_cpd_062_icu
1,NDAR_INVYVVMMD41,NDAR_INVYVVMMD41,02/22/2020,142,F,sd_wave1_arm_3,3,3,3,2,2,1,2,2,1,2,3,1,2
2,NDAR_INVJN2G8BWG,NDAR_INVJN2G8BWG,07/21/2019,143,M,sd_wave1_arm_3,2,3,3,3,0,2,1,0,3,0,1,0,1
3,NDAR_INVJR23U8DW,NDAR_INVJR23U8DW,05/31/2019,128,F,sd_wave1_arm_3,3,3,3,3,0,1,3,1,2,2,2,1,2
4,NDAR_INVYZ353ZBM,NDAR_INVYZ353ZBM,06/03/2019,129,F,sd_wave1_arm_3,3,3,3,3,0,0,2,0,0,2,3,2,3
5,NDAR_INVLNA4879N,NDAR_INVLNA4879N,11/01/2019,126,M,sd_wave1_arm_3,3,3,3,3,0,0,0,0,0,3,1,1,1
6,NDAR_INVLVT4DDY4,NDAR_INVLVT4DDY4,03/08/2019,120,M,sd_wave1_arm_3,1,2,2,2,1,1,2,2,1,1,2,1,1
7,NDAR_INV99DBA2DJ,NDAR_INV99DBA2DJ,04/04/2019,144,F,sd_wave1_arm_3,3,3,3,3,0,1,2,2,3,1,2,2,1
8,NDAR_INV9ANUKVD0,NDAR_INV9ANUKVD0,10/24/2019,153,M,sd_wave1_arm_3,2,2,2,2,0,1,1,2,2,1,1,2,1
9,NDAR_INV9ZXTBCKF,NDAR_INV9ZXTBCKF,09/23/2020,145,F,sd_wave1_arm_3,3,3,3,3,0,0,2,2,0,1,3,1,3
10,NDAR_INVN4F57516,NDAR_INVN4F57516,04/18/2019,123,F,sd_wave1_arm_3,3,3,3,1,0,0,2,0,2,2,3,3,3

In [12]:
parent_personality = parent_personality.iloc[1: , :]
parent_personality.head(10)

,collection_id,abcd_socdev_p_pdis01_id,dataset_id,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,socialdev_ppd_01,...,socialdev_ppd_43,socialdev_ppd_44,socialdev_ppd_45,socialdev_ppd_46,socialdev_ppd_47,socialdev_ppd_48,socialdev_ppd_49,socialdev_ppd_50,socialdev_ppd_51,collection_title
1,2573,12968,47316,NDAR_INVPENZ13BH,NDAR_INVPENZ13BH,04/28/2019,131,M,sd_wave1_arm_3,2,...,2,1,1,1,1,1,0,1,1,Adolescent Brain Cognitive Development Study (...
2,2573,12243,47316,NDAR_INVBF8H4PR1,NDAR_INVBF8H4PR1,07/08/2019,128,M,sd_wave1_arm_3,2,...,1,1,0,0,1,1,0,1,1,Adolescent Brain Cognitive Development Study (...
3,2573,12972,47316,NDAR_INVPGB4E8R7,NDAR_INVPGB4E8R7,09/07/2019,120,M,sd_wave1_arm_3,1,...,2,2,1,2,1,2,1,1,1,Adolescent Brain Cognitive Development Study (...
4,2573,12947,47316,NDAR_INVT2JJ42KE,NDAR_INVT2JJ42KE,11/02/2019,151,F,sd_wave1_arm_3,3,...,1,0,0,1,0,1,0,1,0,Adolescent Brain Cognitive Development Study (...
5,2573,11493,47316,NDAR_INV40UDB664,NDAR_INV40UDB664,09/23/2019,122,F,sd_wave1_arm_3,3,...,1,0,0,1,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
6,2573,13172,47316,NDAR_INVVDTMX4Y4,NDAR_INVVDTMX4Y4,04/03/2019,135,M,sd_wave1_arm_3,2,...,0,0,0,0,0,1,0,1,0,Adolescent Brain Cognitive Development Study (...
7,2573,13173,47316,NDAR_INVVF4AJE7R,NDAR_INVVF4AJE7R,01/30/2020,157,F,sd_wave1_arm_3,3,...,1,1,0,1,0,0,0,0,1,Adolescent Brain Cognitive Development Study (...
8,2573,13184,47316,NDAR_INVW2GVHACV,NDAR_INVW2GVHACV,02/15/2020,136,M,sd_wave1_arm_3,2,...,1,1,0,1,1,1,0,1,1,Adolescent Brain Cognitive Development Study (...
9,2573,13159,47316,NDAR_INVV9G24V48,NDAR_INVV9G24V48,01/30/2020,157,M,sd_wave1_arm_3,1,...,1,1,1,1,0,0,1,1,1,Adolescent Brain Cognitive Development Study (...
10,2573,11408,47316,NDAR_INV0WAF57A4,NDAR_INV0WAF57A4,04/04/2019,144,F,sd_wave1_arm_3,3,...,1,1,0,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...

In [13]:
parent_nij_empathy = parent_personality[["subjectkey", "src_subject_id", "eventname", "socialdev_ppd_01","socialdev_ppd_02", "socialdev_ppd_03",
                                         "socialdev_ppd_04", "socialdev_ppd_07", "socialdev_ppd_08", "socialdev_ppd_09", "socialdev_ppd_10", "socialdev_ppd_11"]]

In [14]:
parent_nij_empathy.head(10)

,subjectkey,src_subject_id,eventname,socialdev_ppd_01,socialdev_ppd_02,socialdev_ppd_03,socialdev_ppd_04,socialdev_ppd_07,socialdev_ppd_08,socialdev_ppd_09,socialdev_ppd_10,socialdev_ppd_11
1,NDAR_INVPENZ13BH,NDAR_INVPENZ13BH,sd_wave1_arm_3,2,2,2,2,1,2,2,1,2
2,NDAR_INVBF8H4PR1,NDAR_INVBF8H4PR1,sd_wave1_arm_3,2,2,2,1,0,1,2,2,2
3,NDAR_INVPGB4E8R7,NDAR_INVPGB4E8R7,sd_wave1_arm_3,1,1,1,3,1,1,1,1,1
4,NDAR_INVT2JJ42KE,NDAR_INVT2JJ42KE,sd_wave1_arm_3,3,3,3,3,0,2,3,2,3
5,NDAR_INV40UDB664,NDAR_INV40UDB664,sd_wave1_arm_3,3,3,3,2,0,3,3,3,3
6,NDAR_INVVDTMX4Y4,NDAR_INVVDTMX4Y4,sd_wave1_arm_3,2,2,2,2,0,1,1,1,1
7,NDAR_INVVF4AJE7R,NDAR_INVVF4AJE7R,sd_wave1_arm_3,3,3,3,3,0,2,2,2,1
8,NDAR_INVW2GVHACV,NDAR_INVW2GVHACV,sd_wave1_arm_3,2,2,2,2,0,1,2,1,1
9,NDAR_INVV9G24V48,NDAR_INVV9G24V48,sd_wave1_arm_3,1,1,1,1,1,1,1,1,1
10,NDAR_INV0WAF57A4,NDAR_INV0WAF57A4,sd_wave1_arm_3,3,3,3,3,0,3,3,3,3

In [15]:
parent_nij_empathy.describe

<bound method NDFrame.describe of             subjectkey    src_subject_id       eventname socialdev_ppd_01  \
1     NDAR_INVPENZ13BH  NDAR_INVPENZ13BH  sd_wave1_arm_3                2
2     NDAR_INVBF8H4PR1  NDAR_INVBF8H4PR1  sd_wave1_arm_3                2
3     NDAR_INVPGB4E8R7  NDAR_INVPGB4E8R7  sd_wave1_arm_3                1
4     NDAR_INVT2JJ42KE  NDAR_INVT2JJ42KE  sd_wave1_arm_3                3
5     NDAR_INV40UDB664  NDAR_INV40UDB664  sd_wave1_arm_3                3
...                ...               ...             ...              ...
2296  NDAR_INVB4CA1YNH  NDAR_INVB4CA1YNH  sd_wave1_arm_3                2
2297  NDAR_INVU2MZM32T  NDAR_INVU2MZM32T  sd_wave1_arm_3                3
2298  NDAR_INV0C471G23  NDAR_INV0C471G23  sd_wave1_arm_3                3
2299  NDAR_INV0CKA3YZX  NDAR_INV0CKA3YZX  sd_wave1_arm_3                1
2300  NDAR_INVBDTGBXYZ  NDAR_INVBDTGBXYZ  sd_wave1_arm_3                2

     socialdev_ppd_02 socialdev_ppd_03 socialdev_ppd_04 socialdev_ppd_07  \
1                   2                2                2                1
2                   2                2                1                0
3                   1                1                3                1
4                   3                3                3                0
5                   3                3                2                0
...               ...              ...              ...              ...
2296                2                3                2                1
2297                3                3                3                0
2298                3                3                3                0
2299                2                1                2                1
2300                2                2                1                0

     socialdev_ppd_08 socialdev_ppd_09 socialdev_ppd_10 socialdev_ppd_11
1                   2                2                1                2
2                   1                2                2                2
3                   1                1                1                1
4                   2                3                2                3
5                   3                3                3                3
...               ...              ...              ...              ...
2296                2                3                1                2
2297                2                2                1                2
2298                3                3                3                3
2299                1                1                2                1
2300                2                2                1                2

[2300 rows x 12 columns]>

In [16]:
empathy_dataframe = pd.merge (youth_nij_empathy, parent_nij_empathy, how="inner", on = ["subjectkey", "src_subject_id","eventname"])

In [17]:
empathy_dataframe.head(10)

,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,socialdev_cpd_053_cads,socialdev_cpd_052_cads,socialdev_cpd_054_cads,socialdev_cpd_051_cads,...,socialdev_cpd_062_icu,socialdev_ppd_01,socialdev_ppd_02,socialdev_ppd_03,socialdev_ppd_04,socialdev_ppd_07,socialdev_ppd_08,socialdev_ppd_09,socialdev_ppd_10,socialdev_ppd_11
0,NDAR_INVYVVMMD41,NDAR_INVYVVMMD41,02/22/2020,142,F,sd_wave1_arm_3,3,3,3,2,...,2,3,3,3,3,0,2,3,3,3
1,NDAR_INVJN2G8BWG,NDAR_INVJN2G8BWG,07/21/2019,143,M,sd_wave1_arm_3,2,3,3,3,...,1,2,2,2,2,0,2,1,2,1
2,NDAR_INVJR23U8DW,NDAR_INVJR23U8DW,05/31/2019,128,F,sd_wave1_arm_3,3,3,3,3,...,2,2,3,3,3,0,2,2,3,2
3,NDAR_INVYZ353ZBM,NDAR_INVYZ353ZBM,06/03/2019,129,F,sd_wave1_arm_3,3,3,3,3,...,3,3,3,3,3,0,3,3,3,3
4,NDAR_INVLNA4879N,NDAR_INVLNA4879N,11/01/2019,126,M,sd_wave1_arm_3,3,3,3,3,...,1,2,2,2,3,0,1,1,1,2
5,NDAR_INVLVT4DDY4,NDAR_INVLVT4DDY4,03/08/2019,120,M,sd_wave1_arm_3,1,2,2,2,...,1,2,2,2,3,1,1,1,2,2
6,NDAR_INV99DBA2DJ,NDAR_INV99DBA2DJ,04/04/2019,144,F,sd_wave1_arm_3,3,3,3,3,...,1,3,3,3,3,0,3,3,3,3
7,NDAR_INV9ANUKVD0,NDAR_INV9ANUKVD0,10/24/2019,153,M,sd_wave1_arm_3,2,2,2,2,...,1,2,2,2,3,1,1,2,1,1
8,NDAR_INV9ZXTBCKF,NDAR_INV9ZXTBCKF,09/23/2020,145,F,sd_wave1_arm_3,3,3,3,3,...,3,3,3,3,3,0,3,3,3,3
9,NDAR_INVN4F57516,NDAR_INVN4F57516,04/18/2019,123,F,sd_wave1_arm_3,3,3,3,1,...,3,3,3,3,2,0,3,3,3,3

In [18]:
empathy_dataframe.describe

<bound method NDFrame.describe of             subjectkey    src_subject_id interview_date interview_age sex  \
0     NDAR_INVYVVMMD41  NDAR_INVYVVMMD41     02/22/2020           142   F
1     NDAR_INVJN2G8BWG  NDAR_INVJN2G8BWG     07/21/2019           143   M
2     NDAR_INVJR23U8DW  NDAR_INVJR23U8DW     05/31/2019           128   F
3     NDAR_INVYZ353ZBM  NDAR_INVYZ353ZBM     06/03/2019           129   F
4     NDAR_INVLNA4879N  NDAR_INVLNA4879N     11/01/2019           126   M
...                ...               ...            ...           ...  ..
2295  NDAR_INVFMV7H24T  NDAR_INVFMV7H24T     08/29/2019           148   M
2296  NDAR_INVV96G6YFB  NDAR_INVV96G6YFB     07/07/2019           155   F
2297  NDAR_INVXMP1CA5E  NDAR_INVXMP1CA5E     08/18/2019           148   F
2298  NDAR_INVK777BPZJ  NDAR_INVK777BPZJ     05/08/2019           134   M
2299  NDAR_INV5P2UAGPW  NDAR_INV5P2UAGPW     04/19/2019           121   F

           eventname socialdev_cpd_053_cads socialdev_cpd_052_cads  \
0     sd_wave1_arm_3                      3                      3
1     sd_wave1_arm_3                      2                      3
2     sd_wave1_arm_3                      3                      3
3     sd_wave1_arm_3                      3                      3
4     sd_wave1_arm_3                      3                      3
...              ...                    ...                    ...
2295  sd_wave1_arm_3                      1                      1
2296  sd_wave1_arm_3                      2                      2
2297  sd_wave1_arm_3                      2                      2
2298  sd_wave1_arm_3                      1                      2
2299  sd_wave1_arm_3                      3                      2

     socialdev_cpd_054_cads socialdev_cpd_051_cads  ... socialdev_cpd_062_icu  \
0                         3                      2  ...                     2
1                         3                      3  ...                     1
2                         3                      3  ...                     2
3                         3                      3  ...                     3
4                         3                      3  ...                     1
...                     ...                    ...  ...                   ...
2295                      1                      1  ...                     1
2296                      3                      2  ...                     1
2297                      3                      2  ...                     2
2298                      0                      0  ...                     0
2299                      3                      2  ...                     2

     socialdev_ppd_01 socialdev_ppd_02 socialdev_ppd_03 socialdev_ppd_04  \
0                   3                3                3                3
1                   2                2                2                2
2                   2                3                3                3
3                   3                3                3                3
4                   2                2                2                3
...               ...              ...              ...              ...
2295                3                3                3                3
2296                3                3                3                3
2297                3                3                3                3
2298                3                3                3                3
2299                2                3                2                3

     socialdev_ppd_07 socialdev_ppd_08 socialdev_ppd_09 socialdev_ppd_10  \
0                   0                2                3                3
1                   0                2                1                2
2                   0                2                2                3
3                   0                3                3                3
4                   0                1                1                1
...               ...              ...              ...              ...
2295                0                2                1                1
2296                0                3                3                3
2297                0                3                3                3
2298                0                3                3                3
2299                0                3                3                1

     socialdev_ppd_11
0                   3
1                   1
2                   2
3                   3
4                   2
...               ...
2295                1
2296                3
2297                3
2298                3
2299                2

[2300 rows x 28 columns]>

In [19]:
#add prosocial
youth_prosocial = youth_prosocial.iloc[1: , :]
youth_prosocial.head(10)

,collection_id,abcd_psb01_id,dataset_id,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,prosocial_q1_y,prosocial_q2_y,prosocial_q3_y,prosocial_admin,collection_title
1,2573,94957,46911,NDAR_INVZ658LRCT,NDAR_INVZ658LRCT,02/19/2020,146,M,2_year_follow_up_y_arm_1,2,2,2,NaN,Adolescent Brain Cognitive Development Study (...
2,2573,94112,46911,NDAR_INVW85HKBUY,NDAR_INVW85HKBUY,01/27/2018,122,M,baseline_year_1_arm_1,2,2,2,NaN,Adolescent Brain Cognitive Development Study (...
3,2573,66546,46911,NDAR_INV8Z4PTP56,NDAR_INV8Z4PTP56,12/22/2018,152,M,2_year_follow_up_y_arm_1,2,2,2,NaN,Adolescent Brain Cognitive Development Study (...
4,2573,66484,46911,NDAR_INV808X1WYW,NDAR_INV808X1WYW,12/26/2018,121,M,1_year_follow_up_y_arm_1,2,2,1,NaN,Adolescent Brain Cognitive Development Study (...
5,2573,73785,46911,NDAR_INVCACFMM98,NDAR_INVCACFMM98,10/24/2018,127,F,1_year_follow_up_y_arm_1,2,2,1,NaN,Adolescent Brain Cognitive Development Study (...
6,2573,56686,46911,NDAR_INV0WTM31V7,NDAR_INV0WTM31V7,06/26/2017,126,M,baseline_year_1_arm_1,2,2,1,NaN,Adolescent Brain Cognitive Development Study (...
7,2573,56706,46911,NDAR_INV0X59EG8X,NDAR_INV0X59EG8X,04/21/2018,111,M,baseline_year_1_arm_1,2,2,2,NaN,Adolescent Brain Cognitive Development Study (...
8,2573,93276,46911,NDAR_INVX51UNV1G,NDAR_INVX51UNV1G,10/28/2020,151,M,2_year_follow_up_y_arm_1,2,1,1,NaN,Adolescent Brain Cognitive Development Study (...
9,2573,93244,46911,NDAR_INVX4GVLBGY,NDAR_INVX4GVLBGY,11/06/2019,149,M,2_year_follow_up_y_arm_1,2,2,2,NaN,Adolescent Brain Cognitive Development Study (...
10,2573,63166,46911,NDAR_INV60X56ELW,NDAR_INV60X56ELW,02/18/2018,121,M,baseline_year_1_arm_1,1,2,1,NaN,Adolescent Brain Cognitive Development Study (...

In [20]:
prosocial_df = youth_prosocial[["subjectkey", "src_subject_id", "interview_date", "interview_age", "sex", "eventname", "prosocial_q1_y", 
                                "prosocial_q2_y", "prosocial_q3_y"]]

In [21]:
parent_prosocial = parent_prosocial.iloc[1: , :]
parent_prosocial.head(10)
parent_prosocial = parent_prosocial[["subjectkey", "src_subject_id", "interview_date", "interview_age", "sex", "eventname", "prosocial_q1_p",
                                     "prosocial_q2_p", "prosocial_q3_p"]]

In [22]:
prosocial_dataframe = pd.merge (prosocial_df, parent_prosocial, how="inner", on = ["subjectkey", "src_subject_id","eventname", "interview_age", "sex", "interview_date"])

In [23]:
prosocial_dataframe.head(10)

,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,prosocial_q1_y,prosocial_q2_y,prosocial_q3_y,prosocial_q1_p,prosocial_q2_p,prosocial_q3_p
0,NDAR_INVZ658LRCT,NDAR_INVZ658LRCT,02/19/2020,146,M,2_year_follow_up_y_arm_1,2,2,2,2,2,2
1,NDAR_INVW85HKBUY,NDAR_INVW85HKBUY,01/27/2018,122,M,baseline_year_1_arm_1,2,2,2,2,2,2
2,NDAR_INV8Z4PTP56,NDAR_INV8Z4PTP56,12/22/2018,152,M,2_year_follow_up_y_arm_1,2,2,2,2,2,1
3,NDAR_INV808X1WYW,NDAR_INV808X1WYW,12/26/2018,121,M,1_year_follow_up_y_arm_1,2,2,1,1,2,1
4,NDAR_INVCACFMM98,NDAR_INVCACFMM98,10/24/2018,127,F,1_year_follow_up_y_arm_1,2,2,1,2,2,2
5,NDAR_INV0WTM31V7,NDAR_INV0WTM31V7,06/26/2017,126,M,baseline_year_1_arm_1,2,2,1,2,2,2
6,NDAR_INV0X59EG8X,NDAR_INV0X59EG8X,04/21/2018,111,M,baseline_year_1_arm_1,2,2,2,0,0,0
7,NDAR_INVX51UNV1G,NDAR_INVX51UNV1G,10/28/2020,151,M,2_year_follow_up_y_arm_1,2,1,1,1,2,2
8,NDAR_INVX4GVLBGY,NDAR_INVX4GVLBGY,11/06/2019,149,M,2_year_follow_up_y_arm_1,2,2,2,2,2,2
9,NDAR_INV60X56ELW,NDAR_INV60X56ELW,02/18/2018,121,M,baseline_year_1_arm_1,1,2,1,2,2,2

In [24]:
prosocial_dataframe.describe

<bound method NDFrame.describe of              subjectkey    src_subject_id interview_date interview_age sex  \
0      NDAR_INVZ658LRCT  NDAR_INVZ658LRCT     02/19/2020           146   M
1      NDAR_INVW85HKBUY  NDAR_INVW85HKBUY     01/27/2018           122   M
2      NDAR_INV8Z4PTP56  NDAR_INV8Z4PTP56     12/22/2018           152   M
3      NDAR_INV808X1WYW  NDAR_INV808X1WYW     12/26/2018           121   M
4      NDAR_INVCACFMM98  NDAR_INVCACFMM98     10/24/2018           127   F
...                 ...               ...            ...           ...  ..
39761  NDAR_INVJ9WR9HD8  NDAR_INVJ9WR9HD8     08/23/2018           139   F
39762  NDAR_INVJG3B0A5J  NDAR_INVJG3B0A5J     02/20/2018           138   M
39763  NDAR_INVR5FD0UXH  NDAR_INVR5FD0UXH     09/05/2019           135   M
39764  NDAR_INVT3366FHE  NDAR_INVT3366FHE     04/06/2019           144   F
39765  NDAR_INVXYF9FXT8  NDAR_INVXYF9FXT8     05/07/2019           142   M

                      eventname prosocial_q1_y prosocial_q2_y prosocial_q3_y  \
0      2_year_follow_up_y_arm_1              2              2              2
1         baseline_year_1_arm_1              2              2              2
2      2_year_follow_up_y_arm_1              2              2              2
3      1_year_follow_up_y_arm_1              2              2              1
4      1_year_follow_up_y_arm_1              2              2              1
...                         ...            ...            ...            ...
39761  1_year_follow_up_y_arm_1              2              2              2
39762  1_year_follow_up_y_arm_1              2              2              2
39763  2_year_follow_up_y_arm_1              2              2              2
39764  2_year_follow_up_y_arm_1              2              2              2
39765  1_year_follow_up_y_arm_1              1              1              2

      prosocial_q1_p prosocial_q2_p prosocial_q3_p
0                  2              2              2
1                  2              2              2
2                  2              2              1
3                  1              2              1
4                  2              2              2
...              ...            ...            ...
39761              2              2              2
39762              2              2              2
39763              2              2              1
39764              2              2              2
39765              2              2              2

[39766 rows x 12 columns]>

In [25]:
#Create a list of NIJ participants to narrow down the larger dataset
nij_ndar_list = empathy_dataframe["subjectkey"].tolist()

In [26]:
prosocial_subset = prosocial_dataframe[prosocial_dataframe["subjectkey"].isin(nij_ndar_list)]

In [27]:
prosocial_subset.describe

<bound method NDFrame.describe of              subjectkey    src_subject_id interview_date interview_age sex  \
9      NDAR_INV60X56ELW  NDAR_INV60X56ELW     02/18/2018           121   M
15     NDAR_INV75642VVU  NDAR_INV75642VVU     12/28/2020           156   M
17     NDAR_INV8CHKACUM  NDAR_INV8CHKACUM     09/12/2017           125   M
22     NDAR_INV1AURDG78  NDAR_INV1AURDG78     10/15/2017           126   F
30     NDAR_INV3WMHUK7W  NDAR_INV3WMHUK7W     12/14/2020           160   F
...                 ...               ...            ...           ...  ..
39749  NDAR_INV0BL9EL2Y  NDAR_INV0BL9EL2Y     01/13/2020           130   F
39750  NDAR_INV0C471G23  NDAR_INV0C471G23     07/09/2018           138   F
39758  NDAR_INVHZJJKJ0D  NDAR_INVHZJJKJ0D     09/21/2017           119   M
39760  NDAR_INVLUDF8E8N  NDAR_INVLUDF8E8N     01/06/2021           148   F
39761  NDAR_INVJ9WR9HD8  NDAR_INVJ9WR9HD8     08/23/2018           139   F

                      eventname prosocial_q1_y prosocial_q2_y prosocial_q3_y  \
9         baseline_year_1_arm_1              1              2              1
15     3_year_follow_up_y_arm_1              2              1              1
17        baseline_year_1_arm_1              2              2              2
22        baseline_year_1_arm_1              2              1              1
30     3_year_follow_up_y_arm_1              2              2              2
...                         ...            ...            ...            ...
39749  2_year_follow_up_y_arm_1              2              2              2
39750  1_year_follow_up_y_arm_1              2              2              1
39758     baseline_year_1_arm_1              2              2              2
39760  3_year_follow_up_y_arm_1              2              2              2
39761  1_year_follow_up_y_arm_1              2              2              2

      prosocial_q1_p prosocial_q2_p prosocial_q3_p
9                  2              2              2
15                 2              2              1
17                 2              2              2
22                 2              2              1
30                 2              2              2
...              ...            ...            ...
39749              2              2              2
39750              2              2              2
39758              2              2              1
39760              2              2              2
39761              2              2              2

[7782 rows x 12 columns]>

In [28]:
#Screen Time Questions

youth_screentime = youth_screentime.iloc[1: , :]
youth_screentime.head (10)

,collection_id,abcd_stq01_id,dataset_id,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,screen1_wkdy_y,...,screen_11_wknd_hr_y,screentime_7_8_wknd_min,screentime_wkdy_school_hr,screentime_wkdy_school_min,screentime_wknd_school_hr,screentime_wknd_school_min,screen_6_wkdy_error_y,screen_wknd_school_error_y,screen_7_8_wknd_min_y,collection_title
1,2573,104429,47288,NDAR_INVREBD8GTZ,NDAR_INVREBD8GTZ,02/10/2018,110,F,baseline_year_1_arm_1,.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
2,2573,106292,47288,NDAR_INVUVW9DC8Y,NDAR_INVUVW9DC8Y,08/09/2018,124,M,1_year_follow_up_y_arm_1,.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
3,2573,110183,47288,NDAR_INVWU8LHADL,NDAR_INVWU8LHADL,03/06/2019,138,F,2_year_follow_up_y_arm_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
4,2573,104373,47288,NDAR_INVPUTKYX3K,NDAR_INVPUTKYX3K,06/14/2019,144,M,2_year_follow_up_y_arm_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
5,2573,104240,47288,NDAR_INVRDF02RR2,NDAR_INVRDF02RR2,03/26/2019,118,F,1_year_follow_up_y_arm_1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
6,2573,110565,47288,NDAR_INVZW8G4W5A,NDAR_INVZW8G4W5A,05/27/2017,124,M,baseline_year_1_arm_1,.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
7,2573,106128,47288,NDAR_INVU6LKLMJU,NDAR_INVU6LKLMJU,05/10/2019,131,F,1_year_follow_up_y_arm_1,.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
8,2573,90466,47288,NDAR_INVFZ8BBNJK,NDAR_INVFZ8BBNJK,04/08/2019,139,F,1_year_follow_up_y_arm_1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
9,2573,98509,47288,NDAR_INVKB30X083,NDAR_INVKB30X083,06/09/2019,133,F,1_year_follow_up_y_arm_1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...
10,2573,98526,47288,NDAR_INVKM0X7RY3,NDAR_INVKM0X7RY3,10/20/2018,131,M,1_year_follow_up_y_arm_1,.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adolescent Brain Cognitive Development Study (...

In [29]:
min_df = (youth_screentime.filter(regex=(".*_min")))
min_df.columns

Index(['screentime_4_wkdy_min', 'screentime_5_wkdy_min',
       'screentime_6_wkdy_min', 'screentime_7_wkdy_min',
       'screentime_8_wkdy_min', 'screentime_9_wkdy_min',
       'screentime_wkdy_typical_min', 'screentime_7_wknd_min',
       'screentime_8_wknd_min', 'screentime_9_wknd_min',
       'screentime_10_wknd_min', 'screentime_11_wknd_min',
       'screentime_12_wknd_min', 'screentime_13_wknd_min',
       'screentime_14_wknd_min', 'screentime_1_wkdy_min',
       'screentime_15_wknd_min', 'screentime_wknd_t_min',
       'screentime_2_wkdy_min', 'screentime_3_wkdy_min',
       'screentime_smq_sm_min', 'screen_14_wknd_min_y', 'screen_4_wkdy_min_y',
       'screen_wkdy_school_min_y', 'screen_9_wkdy_min_y',
       'screen_3_wkdy_min_y', 'screen_wknd_school_min_y',
       'screen_6_wkdy_min_y', 'screen_11_wknd_min_y', 'screen_1_wkdy2_min_y',
       'screen_15_wknd_min_y', 'screen_9_wknd_min_y',
       'screen_wknd_typical_min_y', 'screen_5_wkdy_min_y',
       'screen_8_wkdy_min_y', 'screen_12_wknd_min_y',
       'screen_wkdy_typical_min_y', 'screen_10_wknd_min_y',
       'screentime_1_wkdy2_min', 'screentime_7_8_wknd_min',
       'screentime_wkdy_school_min', 'screentime_wknd_school_min',
       'screen_7_8_wknd_min_y'],
      dtype='object')

In [30]:
youth_screentime_i = youth_screentime[["subjectkey", "src_subject_id", "interview_date", "interview_age", "sex", "eventname",'screen1_wkdy_y', 'screen2_wkdy_y', 
                                       'screen3_wkdy_y', 'screen4_wkdy_y','screen5_wkdy_y', 'screen_wkdy_y', 'screen7_wknd_y', 'screen8_wknd_y',
                                       'screen9_wknd_y', 'screen10_wknd_y', 'screen11_wknd_y','screen12_wknd_y',  
                                     'screentime_5_wkdy_hr', 'screentime_6_wkdy_hr', 'screentime_7_wkdy_hr', 'screentime_8_wkdy_hr', 
                                     'screentime_9_wkdy_hr','screentime_wkdy_typical_hr', 'screentime_7_wknd_hr','screentime_8_wknd_hr', 
                                     'screentime_9_wknd_hr', 'screentime_10_wknd_hr', 'screentime_1_wkdy_hr', 'screentime_11_wknd_hr',
                                     'screentime_12_wknd_hr', 'screentime_13_wknd_hr','screentime_14_wknd_hr', 'screentime_15_wknd_hr', 
                                     'screentime_wknd_typical_hr', 'screentime_2_wkdy_hr', 'screentime_3_wkdy_hr', 'screentime_smq_soc_med_hr',
                                     'screentime_4_wkdy_hr', 'screen_wknd_school_hr_y', 'screen_7_8_wknd_hr_y', 'screen_8_wkdy_hr_y', 
                                     'screen_14_wknd_hr_y', 'screen_wknd_typical_hr_y', 'screen_9_wknd_hr_y', 'screen_3_wkdy_hr_y', 
                                     'screen_4_wkdy_hr_y', 'screen_10_wknd_hr_y', 'screen_wkdy_typical_hr_y', 'screen_9_wkdy_hr_y', 
                                     'screen_wkdy_school_hr_y', 'screen_15_wknd_hr_y', 'screen_12_wknd_hr_y', 'screen_1_wkdy2_hr_y', 
                                     'screen_6_wkdy_hr_y', 'screen_5_wkdy_hr_y', 'screentime_1_wkdy2_hr', 'screentime_7_8_wknd_hr', 'screen_11_wknd_hr_y', 'screentime_4_wkdy_min', 'screentime_5_wkdy_min',
                                     'screentime_6_wkdy_min', 'screentime_7_wkdy_min','screentime_8_wkdy_min', 'screentime_9_wkdy_min','screentime_wkdy_typical_min', 'screentime_7_wknd_min',
                                     'screentime_8_wknd_min', 'screentime_9_wknd_min','screentime_10_wknd_min', 'screentime_11_wknd_min','screentime_12_wknd_min', 'screentime_13_wknd_min',
                                     'screentime_14_wknd_min', 'screentime_1_wkdy_min','screentime_15_wknd_min', 'screentime_wknd_t_min', 'screentime_2_wkdy_min', 'screentime_3_wkdy_min', 'screentime_smq_sm_min', 'screen_14_wknd_min_y', 'screen_4_wkdy_min_y',
                                     'screen_wkdy_school_min_y', 'screen_9_wkdy_min_y','screen_3_wkdy_min_y', 'screen_wknd_school_min_y','screen_6_wkdy_min_y', 'screen_11_wknd_min_y', 'screen_1_wkdy2_min_y', 'screen_15_wknd_min_y', 'screen_9_wknd_min_y',
                                     'screen_wknd_typical_min_y', 'screen_5_wkdy_min_y', 'screen_8_wkdy_min_y', 'screen_12_wknd_min_y', 'screen_wkdy_typical_min_y', 'screen_10_wknd_min_y',
                                     'screentime_1_wkdy2_min', 'screentime_7_8_wknd_min','screentime_wkdy_school_min', 'screentime_wknd_school_min','screen_7_8_wknd_min_y']]

In [31]:
parent_screentime_i = parent_screentime[["subjectkey", "src_subject_id", "interview_date", "interview_age", "sex", "eventname",
                                       "screentime_1_wkdy_hrs_p", "screentime_1_wkdy_min_p", "screentime_1_wknd_hrs_p", "screentime_1_wknd_min_p",]]

In [32]:
screentime_dataframe = pd.merge (youth_screentime_i, parent_screentime_i, how="inner", on = ["subjectkey", "src_subject_id","eventname", "interview_age", "sex", "interview_date"])

In [33]:
screentime_dataframe.head(10)

,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,screen1_wkdy_y,screen2_wkdy_y,screen3_wkdy_y,screen4_wkdy_y,...,screen_10_wknd_min_y,screentime_1_wkdy2_min,screentime_7_8_wknd_min,screentime_wkdy_school_min,screentime_wknd_school_min,screen_7_8_wknd_min_y,screentime_1_wkdy_hrs_p,screentime_1_wkdy_min_p,screentime_1_wknd_hrs_p,screentime_1_wknd_min_p
0,NDAR_INVREBD8GTZ,NDAR_INVREBD8GTZ,02/10/2018,110,F,baseline_year_1_arm_1,.5,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NDAR_INVUVW9DC8Y,NDAR_INVUVW9DC8Y,08/09/2018,124,M,1_year_follow_up_y_arm_1,.5,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NDAR_INVWU8LHADL,NDAR_INVWU8LHADL,03/06/2019,138,F,2_year_follow_up_y_arm_1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4,30,8,0
3,NDAR_INVPUTKYX3K,NDAR_INVPUTKYX3K,06/14/2019,144,M,2_year_follow_up_y_arm_1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6,0,7,0
4,NDAR_INVRDF02RR2,NDAR_INVRDF02RR2,03/26/2019,118,F,1_year_follow_up_y_arm_1,2,.5,1,.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NDAR_INVZW8G4W5A,NDAR_INVZW8G4W5A,05/27/2017,124,M,baseline_year_1_arm_1,.25,.25,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NDAR_INVU6LKLMJU,NDAR_INVU6LKLMJU,05/10/2019,131,F,1_year_follow_up_y_arm_1,.25,2,.5,.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NDAR_INVFZ8BBNJK,NDAR_INVFZ8BBNJK,04/08/2019,139,F,1_year_follow_up_y_arm_1,1,1,.5,.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NDAR_INVKB30X083,NDAR_INVKB30X083,06/09/2019,133,F,1_year_follow_up_y_arm_1,2,1,1,.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NDAR_INVKM0X7RY3,NDAR_INVKM0X7RY3,10/20/2018,131,M,1_year_follow_up_y_arm_1,.5,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
screentime_subset = screentime_dataframe[screentime_dataframe["subjectkey"].isin(nij_ndar_list)]

In [35]:
screentime_subset.describe

<bound method NDFrame.describe of              subjectkey    src_subject_id interview_date interview_age sex  \
5      NDAR_INVZW8G4W5A  NDAR_INVZW8G4W5A     05/27/2017           124   M
8      NDAR_INVKB30X083  NDAR_INVKB30X083     06/09/2019           133   F
21     NDAR_INVUXBAPXMJ  NDAR_INVUXBAPXMJ     09/29/2018           121   F
34     NDAR_INVTH1YJVJ1  NDAR_INVTH1YJVJ1     04/14/2020           160   F
37     NDAR_INVXRBWGD7W  NDAR_INVXRBWGD7W     01/19/2017           131   M
...                 ...               ...            ...           ...  ..
39739  NDAR_INVLH8GZ09D  NDAR_INVLH8GZ09D     07/30/2020           138   M
39743  NDAR_INV4GRV3A5L  NDAR_INV4GRV3A5L     08/05/2020           153   F
39747  NDAR_INV29CHYRH1  NDAR_INV29CHYRH1     07/20/2019           141   F
39748  NDAR_INV4ZMG12VE  NDAR_INV4ZMG12VE     10/28/2020           157   M
39750  NDAR_INV8666P5JN  NDAR_INV8666P5JN     02/27/2018           121   M

                      eventname screen1_wkdy_y screen2_wkdy_y screen3_wkdy_y  \
5         baseline_year_1_arm_1            .25            .25              0
8      1_year_follow_up_y_arm_1              2              1              1
21     1_year_follow_up_y_arm_1             .5              3              0
34     3_year_follow_up_y_arm_1            NaN            NaN            NaN
37        baseline_year_1_arm_1              3              0              0
...                         ...            ...            ...            ...
39739  2_year_follow_up_y_arm_1            NaN            NaN            NaN
39743  2_year_follow_up_y_arm_1            NaN            NaN            NaN
39747  2_year_follow_up_y_arm_1            NaN            NaN            NaN
39748  2_year_follow_up_y_arm_1            NaN            NaN            NaN
39750  1_year_follow_up_y_arm_1              0              0              0

      screen4_wkdy_y  ... screen_10_wknd_min_y screentime_1_wkdy2_min  \
5                  0  ...                  NaN                    NaN
8                .25  ...                  NaN                    NaN
21               .25  ...                  NaN                    NaN
34               NaN  ...                  NaN                      0
37                 0  ...                  NaN                    NaN
...              ...  ...                  ...                    ...
39739            NaN  ...                  NaN                    NaN
39743            NaN  ...                  NaN                    NaN
39747            NaN  ...                  NaN                    NaN
39748            NaN  ...                  NaN                    NaN
39750            .25  ...                  NaN                    NaN

      screentime_7_8_wknd_min screentime_wkdy_school_min  \
5                         NaN                        NaN
8                         NaN                        NaN
21                        NaN                        NaN
34                          0                          0
37                        NaN                        NaN
...                       ...                        ...
39739                     NaN                        NaN
39743                     NaN                        NaN
39747                     NaN                        NaN
39748                     NaN                         30
39750                     NaN                        NaN

      screentime_wknd_school_min screen_7_8_wknd_min_y  \
5                            NaN                   NaN
8                            NaN                   NaN
21                           NaN                   NaN
34                            15                   NaN
37                           NaN                   NaN
...                          ...                   ...
39739                        NaN                   NaN
39743                        NaN                   NaN
39747                        NaN                   NaN
39748                        NaN                   NaN
39750                        NaN                   NaN

      screentime_1_wkdy_hrs_p screentime_1_wkdy_min_p screentime_1_wknd_hrs_p  \
5                         NaN                     NaN                     NaN
8                         NaN                     NaN                     NaN
21                        NaN                     NaN                     NaN
34                          4                       0                       6
37                        NaN                     NaN                     NaN
...                       ...                     ...                     ...
39739                      10                       0                      10
39743                       6                      15                       6
39747                       1                       0                       2
39748                       2                       0                       4
39750                     NaN                     NaN                     NaN

      screentime_1_wknd_min_p
5                         NaN
8                         NaN
21                        NaN
34                          0
37                        NaN
...                       ...
39739                       0
39743                      15
39747                       0
39748                       0
39750                     NaN

[7782 rows x 106 columns]>

In [36]:
#add in cog empathy and demographics
cog_empathy = pd.read_csv("abcd_pssrs01.txt", delimiter='\t', na_values=[""], low_memory= False)

In [37]:
cog_empathy = cog_empathy.iloc[1: , :]
cog_empathy.head(10)

,collection_id,abcd_pssrs01_id,dataset_id,subjectkey,src_subject_id,interview_age,interview_date,sex,eventname,ssrs_select_language___1,...,ssrs_16_p,ssrs_18_p,ssrs_24_p,ssrs_29_p,ssrs_35_p,ssrs_37_p,ssrs_39_p,ssrs_42_p,ssrs_58_p,collection_title
1,2573,23304,47225,NDAR_INVL00DXXD5,NDAR_INVL00DXXD5,137,03/06/2018,M,1_year_follow_up_y_arm_1,0,...,1,3,1,3,1,3,4,1,2,Adolescent Brain Cognitive Development Study (...
2,2573,24271,47225,NDAR_INVRPFT44DU,NDAR_INVRPFT44DU,133,07/25/2019,F,1_year_follow_up_y_arm_1,0,...,1,1,1,1,1,1,1,1,1,Adolescent Brain Cognitive Development Study (...
3,2573,24282,47225,NDAR_INVRRFZW203,NDAR_INVRRFZW203,133,03/06/2019,M,1_year_follow_up_y_arm_1,0,...,1,1,2,1,1,1,1,1,1,Adolescent Brain Cognitive Development Study (...
4,2573,25257,47225,NDAR_INVTDU8UBTD,NDAR_INVTDU8UBTD,124,08/27/2019,M,1_year_follow_up_y_arm_1,1,...,1,1,2,1,2,1,1,1,1,Adolescent Brain Cognitive Development Study (...
5,2573,23525,47225,NDAR_INVR6FAP3A7,NDAR_INVR6FAP3A7,130,01/11/2019,M,1_year_follow_up_y_arm_1,0,...,1,1,1,1,1,1,1,1,1,Adolescent Brain Cognitive Development Study (...
6,2573,23559,47225,NDAR_INVR9JZP8TC,NDAR_INVR9JZP8TC,135,07/16/2019,F,1_year_follow_up_y_arm_1,1,...,1,3,1,1,2,2,2,1,1,Adolescent Brain Cognitive Development Study (...
7,2573,23177,47225,NDAR_INVL6EFKUHV,NDAR_INVL6EFKUHV,144,06/28/2019,M,1_year_follow_up_y_arm_1,0,...,1,1,1,1,1,1,2,1,1,Adolescent Brain Cognitive Development Study (...
8,2573,23179,47225,NDAR_INVL6MBKZ9X,NDAR_INVL6MBKZ9X,128,06/18/2019,F,1_year_follow_up_y_arm_1,0,...,1,1,1,1,1,1,1,1,1,Adolescent Brain Cognitive Development Study (...
9,2573,23423,47225,NDAR_INVXEBWBPYN,NDAR_INVXEBWBPYN,141,10/07/2018,M,1_year_follow_up_y_arm_1,0,...,1,1,1,1,1,1,1,1,1,Adolescent Brain Cognitive Development Study (...
10,2573,25629,47225,NDAR_INVYEC4J77T,NDAR_INVYEC4J77T,120,04/06/2018,F,1_year_follow_up_y_arm_1,0,...,1,1,1,2,1,1,1,1,1,Adolescent Brain Cognitive Development Study (...

In [38]:
stq_pro_df = pd.merge (screentime_subset, prosocial_subset, how="inner", on = ["subjectkey", "src_subject_id","eventname", "interview_age", "sex", "interview_date"])

In [39]:
cog_empathy = cog_empathy [["subjectkey", "src_subject_id", "interview_date", "interview_age", "sex", "eventname",
                           "ssrs_15r_p", "ssrs_37_p"]]

In [40]:
cog_empathy_sub = cog_empathy[cog_empathy["subjectkey"].isin(nij_ndar_list)]

In [41]:
stq_pro_cog_df = pd.merge (stq_pro_df, cog_empathy, how="inner", on = ["subjectkey", "src_subject_id","eventname", "interview_age", "sex", "interview_date"])

In [42]:
#subset demo
demographics = demographics.iloc[1: , :]
demo_subset = demographics[demographics["subjectkey"].isin(nij_ndar_list)]

In [43]:
demo_subset.describe

<bound method NDFrame.describe of       collection_id abcd_lpds01_id dataset_id        subjectkey  \
11             2573          81706      47217  NDAR_INVHJULNANY
16             2573          90721      47217  NDAR_INVRMV0P0FV
21             2573          71005      47217  NDAR_INV8PMAFPCV
22             2573          71127      47217  NDAR_INV98096D02
36             2573          64941      47217  NDAR_INV4LCR7BFU
...             ...            ...        ...               ...
39702          2573          86721      47217  NDAR_INVMR60CAWU
39717          2573          73605      47217  NDAR_INVAZWRU7C4
39724          2573          98034      47217  NDAR_INVZ2BXG0C8
39745          2573          67208      47217  NDAR_INV6EDUREMP
39762          2573          61401      47217  NDAR_INV1GVYL05C

         src_subject_id interview_age interview_date sex  \
11     NDAR_INVHJULNANY           122     03/01/2017   M
16     NDAR_INVRMV0P0FV           144     04/16/2020   F
21     NDAR_INV8PMAFPCV           141     07/25/2019   F
22     NDAR_INV98096D02           150     10/21/2020   M
36     NDAR_INV4LCR7BFU           130     11/06/2018   M
...                 ...           ...            ...  ..
39702  NDAR_INVMR60CAWU           131     04/03/2018   M
39717  NDAR_INVAZWRU7C4           130     12/15/2018   F
39724  NDAR_INVZ2BXG0C8           140     08/19/2020   M
39745  NDAR_INV6EDUREMP           107     10/13/2018   M
39762  NDAR_INV1GVYL05C           123     11/06/2018   F

                      eventname demo_l_p_select_language___1  ...  \
11        baseline_year_1_arm_1                            0  ...
16     3_year_follow_up_y_arm_1                            0  ...
21     1_year_follow_up_y_arm_1                            0  ...
22     2_year_follow_up_y_arm_1                            0  ...
36     1_year_follow_up_y_arm_1                            0  ...
...                         ...                          ...  ...
39702  1_year_follow_up_y_arm_1                            0  ...
39717  1_year_follow_up_y_arm_1                            0  ...
39724  2_year_follow_up_y_arm_1                            0  ...
39745     baseline_year_1_arm_1                            0  ...
39762  1_year_follow_up_y_arm_1                            0  ...

      demo_nat_lang_3_yrs_other_p_13 demo_nat_lang_3_yrs_other_p_14  \
11                                 0                              0
16                                 0                              0
21                                 0                              0
22                                 0                              0
36                                 0                              0
...                              ...                            ...
39702                              0                              0
39717                              0                              0
39724                              0                              0
39745                              0                              0
39762                              0                              0

      demo_nat_lang_3_p demo_nat_lang_3_yrs_eng_p___1  \
11                  NaN                             0
16                    0                             0
21                  NaN                             0
22                  NaN                             0
36                  NaN                             0
...                 ...                           ...
39702               NaN                             0
39717               NaN                             0
39724               NaN                             0
39745               NaN                             0
39762               NaN                             0

      demo_nat_lang_3_yrs_eng_p___2 demo_nat_lang_3_yrs_eng_p___3  \
11                                0                             0
16                                0                             0
21                                0                             0
22                                0                             0
36                                0                             0
...                             ...                           ...
39702                             0                             0
39717                             0                             0
39724                             0                             0
39745                             0                             0
39762                             0                             0

      demo_nat_lang_3_yrs_eng_p___4 demo_nat_lang_3_yrs_eng_p___5  \
11                                0                             0
16                                0                             0
21                                0                             0
22                                0                             0
36                                0                             0
...                             ...                           ...
39702                             0                             0
39717                             0                             0
39724                             0                             0
39745                             0                             0
39762                             0                             0

      demo_nat_lang_3_yrs_eng_p___6  \
11                                0
16                                0
21                                0
22                                0
36                                0
...                             ...
39702                             0
39717                             0
39724                             0
39745                             0
39762                             0

                                        collection_title
11     Adolescent Brain Cognitive Development Study (...
16     Adolescent Brain Cognitive Development Study (...
21     Adolescent Brain Cognitive Development Study (...
22     Adolescent Brain Cognitive Development Study (...
36     Adolescent Brain Cognitive Development Study (...
...                                                  ...
39702  Adolescent Brain Cognitive Development Study (...
39717  Adolescent Brain Cognitive Development Study (...
39724  Adolescent Brain Cognitive Development Study (...
39745  Adolescent Brain Cognitive Development Study (...
39762  Adolescent Brain Cognitive Development Study (...

[7782 rows x 160 columns]>

In [44]:
all_abcd_df = pd.merge (stq_pro_cog_df, demo_subset, how="inner", on = ["subjectkey", "src_subject_id","eventname", "interview_age", "sex", "interview_date"])

In [45]:
all_abcd_df.head(10)

,subjectkey,src_subject_id,interview_date,interview_age,sex,eventname,screen1_wkdy_y,screen2_wkdy_y,screen3_wkdy_y,screen4_wkdy_y,...,demo_nat_lang_3_yrs_other_p_13,demo_nat_lang_3_yrs_other_p_14,demo_nat_lang_3_p,demo_nat_lang_3_yrs_eng_p___1,demo_nat_lang_3_yrs_eng_p___2,demo_nat_lang_3_yrs_eng_p___3,demo_nat_lang_3_yrs_eng_p___4,demo_nat_lang_3_yrs_eng_p___5,demo_nat_lang_3_yrs_eng_p___6,collection_title
0,NDAR_INVKB30X083,NDAR_INVKB30X083,06/09/2019,133,F,1_year_follow_up_y_arm_1,2,1,1,.25,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
1,NDAR_INVUXBAPXMJ,NDAR_INVUXBAPXMJ,09/29/2018,121,F,1_year_follow_up_y_arm_1,.5,3,0,.25,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
2,NDAR_INV82HYA45D,NDAR_INV82HYA45D,07/11/2018,129,M,1_year_follow_up_y_arm_1,.25,2,3,.5,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
3,NDAR_INVCEWUA63Z,NDAR_INVCEWUA63Z,04/03/2019,141,F,1_year_follow_up_y_arm_1,2,4,0,4,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
4,NDAR_INVD3TWTXDB,NDAR_INVD3TWTXDB,12/02/2018,130,M,1_year_follow_up_y_arm_1,4,1,2,0,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
5,NDAR_INV6EU13388,NDAR_INV6EU13388,04/09/2019,140,F,1_year_follow_up_y_arm_1,.5,0,1,.5,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
6,NDAR_INVNHKNUNA6,NDAR_INVNHKNUNA6,07/15/2019,130,M,1_year_follow_up_y_arm_1,0,.25,1,0,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
7,NDAR_INVCK8WM58K,NDAR_INVCK8WM58K,12/14/2018,123,M,1_year_follow_up_y_arm_1,.25,4,4,.25,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
8,NDAR_INVNVY8KZHN,NDAR_INVNVY8KZHN,08/31/2018,143,M,1_year_follow_up_y_arm_1,.25,.25,.25,.25,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...
9,NDAR_INVRHGBHZ4A,NDAR_INVRHGBHZ4A,07/09/2019,131,F,1_year_follow_up_y_arm_1,2,.25,0,0,...,0,0,NaN,0,0,0,0,0,0,Adolescent Brain Cognitive Development Study (...

In [46]:
master_df = pd.merge ( all_abcd_df, empathy_dataframe, how="inner", on = ["subjectkey", "src_subject_id"])

In [47]:
master_df.describe

<bound method NDFrame.describe of             subjectkey    src_subject_id interview_date_x interview_age_x  \
0     NDAR_INVKB30X083  NDAR_INVKB30X083       06/09/2019             133
1     NDAR_INVUXBAPXMJ  NDAR_INVUXBAPXMJ       09/29/2018             121
2     NDAR_INV82HYA45D  NDAR_INV82HYA45D       07/11/2018             129
3     NDAR_INVCEWUA63Z  NDAR_INVCEWUA63Z       04/03/2019             141
4     NDAR_INVD3TWTXDB  NDAR_INVD3TWTXDB       12/02/2018             130
...                ...               ...              ...             ...
2224  NDAR_INVRMV0P0FV  NDAR_INVRMV0P0FV       07/05/2018             122
2225  NDAR_INVWXP08CYK  NDAR_INVWXP08CYK       10/11/2019             121
2226  NDAR_INVXXYY59XX  NDAR_INVXXYY59XX       03/13/2018             125
2227  NDAR_INVK427BMWY  NDAR_INVK427BMWY       10/26/2018             131
2228  NDAR_INV8666P5JN  NDAR_INV8666P5JN       02/27/2018             121

     sex_x               eventname_x screen1_wkdy_y screen2_wkdy_y  \
0        F  1_year_follow_up_y_arm_1              2              1
1        F  1_year_follow_up_y_arm_1             .5              3
2        M  1_year_follow_up_y_arm_1            .25              2
3        F  1_year_follow_up_y_arm_1              2              4
4        M  1_year_follow_up_y_arm_1              4              1
...    ...                       ...            ...            ...
2224     F  1_year_follow_up_y_arm_1              0              1
2225     M  1_year_follow_up_y_arm_1              2              4
2226     M  1_year_follow_up_y_arm_1              1             .5
2227     F  1_year_follow_up_y_arm_1              2              3
2228     M  1_year_follow_up_y_arm_1              0              0

     screen3_wkdy_y screen4_wkdy_y  ... socialdev_cpd_062_icu  \
0                 1            .25  ...                     2
1                 0            .25  ...                     3
2                 3             .5  ...                     3
3                 0              4  ...                     3
4                 2              0  ...                     2
...             ...            ...  ...                   ...
2224            .25              1  ...                     3
2225              4              0  ...                     3
2226              3              0  ...                     1
2227              2              0  ...                     3
2228              0            .25  ...                     1

     socialdev_ppd_01 socialdev_ppd_02 socialdev_ppd_03 socialdev_ppd_04  \
0                   3                3                3                3
1                   3                3                3                3
2                   3                3                3                3
3                   3                2                2                3
4                   3                2                2                3
...               ...              ...              ...              ...
2224                3                3                3                3
2225                3                3                3                3
2226                3                3                3                3
2227                3                3                3                3
2228                3                3                2                2

     socialdev_ppd_07 socialdev_ppd_08 socialdev_ppd_09 socialdev_ppd_10  \
0                   0                2                2                2
1                   0                3                3                3
2                   0                2                2                1
3                   0                3                3                3
4                   0                3                3                3
...               ...              ...              ...              ...
2224                0                2                3                3
2225                0                3                3                3
2226                0                2                2                3
2227                0                2                3                2
2228                0                1                1                1

     socialdev_ppd_11
0                   2
1                   3
2                   2
3                   3
4                   2
...               ...
2224                3
2225                3
2226                3
2227                2
2228                2

[2229 rows x 294 columns]>

In [48]:
master_df.head (30)

,subjectkey,src_subject_id,interview_date_x,interview_age_x,sex_x,eventname_x,screen1_wkdy_y,screen2_wkdy_y,screen3_wkdy_y,screen4_wkdy_y,...,socialdev_cpd_062_icu,socialdev_ppd_01,socialdev_ppd_02,socialdev_ppd_03,socialdev_ppd_04,socialdev_ppd_07,socialdev_ppd_08,socialdev_ppd_09,socialdev_ppd_10,socialdev_ppd_11
0,NDAR_INVKB30X083,NDAR_INVKB30X083,06/09/2019,133,F,1_year_follow_up_y_arm_1,2,1,1,.25,...,2,3,3,3,3,0,2,2,2,2
1,NDAR_INVUXBAPXMJ,NDAR_INVUXBAPXMJ,09/29/2018,121,F,1_year_follow_up_y_arm_1,.5,3,0,.25,...,3,3,3,3,3,0,3,3,3,3
2,NDAR_INV82HYA45D,NDAR_INV82HYA45D,07/11/2018,129,M,1_year_follow_up_y_arm_1,.25,2,3,.5,...,3,3,3,3,3,0,2,2,1,2
3,NDAR_INVCEWUA63Z,NDAR_INVCEWUA63Z,04/03/2019,141,F,1_year_follow_up_y_arm_1,2,4,0,4,...,3,3,2,2,3,0,3,3,3,3
4,NDAR_INVD3TWTXDB,NDAR_INVD3TWTXDB,12/02/2018,130,M,1_year_follow_up_y_arm_1,4,1,2,0,...,2,3,2,2,3,0,3,3,3,2
5,NDAR_INV6EU13388,NDAR_INV6EU13388,04/09/2019,140,F,1_year_follow_up_y_arm_1,.5,0,1,.5,...,3,3,3,3,2,0,3,3,2,2
6,NDAR_INVNHKNUNA6,NDAR_INVNHKNUNA6,07/15/2019,130,M,1_year_follow_up_y_arm_1,0,.25,1,0,...,2,3,3,3,3,0,3,3,3,3
7,NDAR_INVCK8WM58K,NDAR_INVCK8WM58K,12/14/2018,123,M,1_year_follow_up_y_arm_1,.25,4,4,.25,...,3,3,3,2,3,0,3,3,3,3
8,NDAR_INVNVY8KZHN,NDAR_INVNVY8KZHN,08/31/2018,143,M,1_year_follow_up_y_arm_1,.25,.25,.25,.25,...,2,3,3,2,3,0,3,3,3,2
9,NDAR_INVRHGBHZ4A,NDAR_INVRHGBHZ4A,07/09/2019,131,F,1_year_follow_up_y_arm_1,2,.25,0,0,...,2,3,3,3,3,0,2,2,1,2
10,NDAR_INVCM8902RM,NDAR_INVCM8902RM,05/08/2019,141,M,1_year_follow_up_y_arm_1,.5,2,4,0,...,1,1,1,1,1,1,1,1,1,1
11,NDAR_INV422B2397,NDAR_INV422B2397,10/27/2019,129,F,1_year_follow_up_y_arm_1,.25,2,2,0,...,3,3,3,3,3,0,2,3,2,3
12,NDAR_INVCR5CRNZU,NDAR_INVCR5CRNZU,02/27/2019,131,M,1_year_follow_up_y_arm_1,0,0,0,0,...,2,1,1,1,2,1,1,1,0,1
13,NDAR_INVZ0NPTXMB,NDAR_INVZ0NPTXMB,08/22/2019,140,M,1_year_follow_up_y_arm_1,2,.25,2,0,...,1,2,2,2,1,0,2,2,2,2
14,NDAR_INVVN0L0E6W,NDAR_INVVN0L0E6W,08/08/2018,128,F,1_year_follow_up_y_arm_1,2,1,.5,.5,...,3,1,1,0,1,1,0,0,1,0
15,NDAR_INV7TJ9713F,NDAR_INV7TJ9713F,01/02/2019,142,M,1_year_follow_up_y_arm_1,.5,1,2,.5,...,2,3,3,2,3,0,2,2,1,2
16,NDAR_INVUEPAL53D,NDAR_INVUEPAL53D,07/12/2018,129,F,1_year_follow_up_y_arm_1,.5,.5,.25,.25,...,2,3,3,3,3,0,3,3,1,3
17,NDAR_INVMENCHP62,NDAR_INVMENCHP62,04/09/2018,128,M,1_year_follow_up_y_arm_1,1,3,4,4,...,1,3,2,3,1,0,3,2,2,2
18,NDAR_INVY0CRE49N,NDAR_INVY0CRE49N,10/09/2019,135,M,1_year_follow_up_y_arm_1,1,2,1,1,...,1,2,2,2,2,0,2,2,1,1
19,NDAR_INVM6LNBP2L,NDAR_INVM6LNBP2L,05/15/2019,141,M,1_year_follow_up_y_arm_1,2,1,1,1,...,2,2,3,1,3,0,1,2,2,2
20,NDAR_INVY4DLE2ZX,NDAR_INVY4DLE2ZX,02/16/2018,143,F,1_year_follow_up_y_arm_1,1,.25,1,.25,...,2,3,3,2,3,0,2,1,2,2
21,NDAR_INVHKYD8UCZ,NDAR_INVHKYD8UCZ,10/25/2018,145,F,1_year_follow_up_y_arm_1,0,1,1,.5,...,3,3,3,3,2,0,3,3,2,3
22,NDAR_INV589PDMA0,NDAR_INV589PDMA0,08/02/2019,125,M,1_year_follow_up_y_arm_1,.25,1,3,.25,...,1,2,2,2,1,0,1,1,1,2
23,NDAR_INV1MF1L9LR,NDAR_INV1MF1L9LR,01/24/2018,137,M,1_year_follow_up_y_arm_1,1,2,4,1,...,3,2,3,3,3,0,2,2,2,2
24,NDAR_INV4BKN34GB,NDAR_INV4BKN34GB,02/16/2018,124,F,1_year_follow_up_y_arm_1,.5,1,.5,1,...,2,3,3,3,2,0,1,1,1,2
25,NDAR_INV7VG73XLG,NDAR_INV7VG73XLG,01/31/2019,133,F,1_year_follow_up_y_arm_1,1,.5,1,.5,...,3,3,3,3,3,0,3,3,3,3
26,NDAR_INV8GEUGXPD,NDAR_INV8GEUGXPD,07/09/2018,143,F,1_year_follow_up_y_arm_1,1,.5,.25,1,...,2,2,2,1,2,0,1,1,1,1
27,NDAR_INVX718NUYK,NDAR_INVX718NUYK,11/05/2018,130,M,1_year_follow_up_y_arm_1,1,.25,3,.25,...,3,3,3,3,3,0,3,3,3,3
28,NDAR_INVA4N4XMZ4,NDAR_INVA4N4XMZ4,12/05/2018,129,F,1_year_follow_up_y_arm_1,1,1,.5,.5,...,2,3,3,3,3,0,3,3,3,3
29,NDAR_INVC4XAJGAN,NDAR_INVC4XAJGAN,07/18/2018,138,M,1_year_follow_up_y_arm_1,.5,0,0,0,...,2,2,2,2,3,0,1,1,1,1

In [49]:
#reverse coding
def reverseScoring(df, high, cols):
    df[cols] = high - df[cols]
    return df

In [50]:
master_df['socialdev_cpd_057_icu'] = master_df['socialdev_cpd_057_icu'].astype('f')

master_df['socialdev_cpd_057_icu'] = 3 - master_df['socialdev_cpd_057_icu']

In [51]:
cols = ["socialdev_cpd_057_icu", "socialdev_ppd_07","socialdev_cpd_002", "ssrs_15r_p","ssrs_37_p", "socialdev_cpd_039"]
for x in cols:
    master_df[x] = master_df[x].astype('f')

In [52]:
col1 = ["socialdev_cpd_057_icu", "socialdev_ppd_07","socialdev_cpd_002", "socialdev_cpd_039"]
col2 = ["ssrs_15r_p","ssrs_37_p"]

In [53]:
reverseScoring (master_df, 3, col1)
reverseScoring (master_df, 4, col2)

,subjectkey,src_subject_id,interview_date_x,interview_age_x,sex_x,eventname_x,screen1_wkdy_y,screen2_wkdy_y,screen3_wkdy_y,screen4_wkdy_y,...,socialdev_cpd_062_icu,socialdev_ppd_01,socialdev_ppd_02,socialdev_ppd_03,socialdev_ppd_04,socialdev_ppd_07,socialdev_ppd_08,socialdev_ppd_09,socialdev_ppd_10,socialdev_ppd_11
0,NDAR_INVKB30X083,NDAR_INVKB30X083,06/09/2019,133,F,1_year_follow_up_y_arm_1,2,1,1,.25,...,2,3,3,3,3,3.0,2,2,2,2
1,NDAR_INVUXBAPXMJ,NDAR_INVUXBAPXMJ,09/29/2018,121,F,1_year_follow_up_y_arm_1,.5,3,0,.25,...,3,3,3,3,3,3.0,3,3,3,3
2,NDAR_INV82HYA45D,NDAR_INV82HYA45D,07/11/2018,129,M,1_year_follow_up_y_arm_1,.25,2,3,.5,...,3,3,3,3,3,3.0,2,2,1,2
3,NDAR_INVCEWUA63Z,NDAR_INVCEWUA63Z,04/03/2019,141,F,1_year_follow_up_y_arm_1,2,4,0,4,...,3,3,2,2,3,3.0,3,3,3,3
4,NDAR_INVD3TWTXDB,NDAR_INVD3TWTXDB,12/02/2018,130,M,1_year_follow_up_y_arm_1,4,1,2,0,...,2,3,2,2,3,3.0,3,3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2224,NDAR_INVRMV0P0FV,NDAR_INVRMV0P0FV,07/05/2018,122,F,1_year_follow_up_y_arm_1,0,1,.25,1,...,3,3,3,3,3,3.0,2,3,3,3
2225,NDAR_INVWXP08CYK,NDAR_INVWXP08CYK,10/11/2019,121,M,1_year_follow_up_y_arm_1,2,4,4,0,...,3,3,3,3,3,3.0,3,3,3,3
2226,NDAR_INVXXYY59XX,NDAR_INVXXYY59XX,03/13/2018,125,M,1_year_follow_up_y_arm_1,1,.5,3,0,...,1,3,3,3,3,3.0,2,2,3,3
2227,NDAR_INVK427BMWY,NDAR_INVK427BMWY,10/26/2018,131,F,1_year_follow_up_y_arm_1,2,3,2,0,...,3,3,3,3,3,3.0,2,3,2,2
2228,NDAR_INV8666P5JN,NDAR_INV8666P5JN,02/27/2018,121,M,1_year_follow_up_y_arm_1,0,0,0,.25,...,1,3,3,2,2,3.0,1,1,1,2

In [54]:
turn_me_into_a_float_daddy = ["socialdev_cpd_053_cads","socialdev_cpd_052_cads", "socialdev_cpd_054_cads", "socialdev_cpd_051_cads","socialdev_cpd_057_icu", 
                              "socialdev_ppd_03", "socialdev_ppd_02", "socialdev_ppd_04", "socialdev_ppd_07", "socialdev_ppd_01", 
                              "socialdev_cpd_002", "socialdev_cpd_049", "socialdev_cpd_035", 
                              "ssrs_15r_p", "ssrs_37_p", "socialdev_cpd_035", 
                              "prosocial_q1_y", "prosocial_q2_y", "prosocial_q3_y", "socialdev_cpd_059_cads", "socialdev_cpd_060_cads", "socialdev_cpd_061_cads", "socialdev_cpd_062_icu",
                              "prosocial_q1_p", "prosocial_q2_p", "prosocial_q3_p", "socialdev_ppd_08", "socialdev_ppd_09", "socialdev_ppd_10", "socialdev_ppd_11"]
for x in turn_me_into_a_float_daddy:
    master_df[x] = master_df[x].fillna(0).astype('int32')

In [55]:
#Making Sumscores
#screentime average weekday + weekend
#make an average for baseline
#probably simplify stq df
#sympathy
#affective empathy
#cog empathy
#prosocial

master_df["sympathy_y"] = (master_df["socialdev_cpd_053_cads"].fillna(0) + master_df["socialdev_cpd_052_cads"].fillna(0) + master_df["socialdev_cpd_054_cads"].fillna(0) + master_df["socialdev_cpd_051_cads"].fillna(0) + master_df["socialdev_cpd_057_icu"].fillna(0))
master_df["sympathy_p"] = master_df["socialdev_ppd_03"] + master_df["socialdev_ppd_02"] + master_df["socialdev_ppd_04"] + master_df["socialdev_ppd_07"] + master_df["socialdev_ppd_01"]
master_df["affective_empathy"] = master_df["socialdev_cpd_002"] + master_df["socialdev_cpd_049"] + master_df["socialdev_cpd_035"]
master_df["cognitive_empathy"] = master_df["ssrs_15r_p"] + master_df["ssrs_37_p"] + master_df["socialdev_cpd_035"]
master_df["empathy_total"] = master_df["sympathy_y"]+ master_df["sympathy_p"] + master_df["affective_empathy"]+master_df["cognitive_empathy"]
master_df["prosocial_y"] = master_df["prosocial_q1_y"] + master_df["prosocial_q2_y"]+ master_df["prosocial_q3_y"] + master_df["socialdev_cpd_059_cads"]+ master_df["socialdev_cpd_060_cads"]+ master_df["socialdev_cpd_061_cads"]+ master_df["socialdev_cpd_062_icu"]
master_df["prosocial_p"] = master_df["prosocial_q1_p"] + master_df["prosocial_q2_p"]+ master_df["prosocial_q3_p"] + master_df["socialdev_ppd_08"]+ master_df["socialdev_ppd_09"]+ master_df["socialdev_ppd_10"]+ master_df["socialdev_ppd_11"]
master_df["prosocial_total"] = master_df["prosocial_p"] + master_df["prosocial_y"]

In [56]:
time_to_float = ['screen1_wkdy_y', 'screen2_wkdy_y', 'screen3_wkdy_y', 'screen4_wkdy_y','screen5_wkdy_y', 'screen_wkdy_y', 'screen7_wknd_y', 'screen8_wknd_y',
                 'screen9_wknd_y', 'screen10_wknd_y', 'screen11_wknd_y','screen12_wknd_y', 'screentime_5_wkdy_hr', 'screentime_6_wkdy_hr', 'screentime_7_wkdy_hr', 'screentime_8_wkdy_hr', 
                                     'screentime_9_wkdy_hr','screentime_wkdy_typical_hr', 'screentime_7_wknd_hr','screentime_8_wknd_hr', 
                                     'screentime_9_wknd_hr', 'screentime_10_wknd_hr', 'screentime_1_wkdy_hr', 'screentime_11_wknd_hr',
                                     'screentime_12_wknd_hr', 'screentime_13_wknd_hr','screentime_14_wknd_hr', 'screentime_15_wknd_hr', 
                                     'screentime_wknd_typical_hr', 'screentime_2_wkdy_hr', 'screentime_3_wkdy_hr', 'screentime_smq_soc_med_hr',
                                     'screentime_4_wkdy_hr', 'screen_wknd_school_hr_y', 'screen_7_8_wknd_hr_y', 'screen_8_wkdy_hr_y', 
                                     'screen_14_wknd_hr_y', 'screen_wknd_typical_hr_y', 'screen_9_wknd_hr_y', 'screen_3_wkdy_hr_y', 
                                     'screen_4_wkdy_hr_y', 'screen_10_wknd_hr_y', 'screen_wkdy_typical_hr_y', 'screen_9_wkdy_hr_y', 
                                     'screen_wkdy_school_hr_y', 'screen_15_wknd_hr_y', 'screen_12_wknd_hr_y', 'screen_1_wkdy2_hr_y', 
                                     'screen_6_wkdy_hr_y', 'screen_5_wkdy_hr_y', 'screentime_1_wkdy2_hr', 'screentime_7_8_wknd_hr', 'screen_11_wknd_hr_y', 'screentime_4_wkdy_min', 'screentime_5_wkdy_min',
                                     'screentime_6_wkdy_min', 'screentime_7_wkdy_min','screentime_8_wkdy_min', 'screentime_9_wkdy_min','screentime_wkdy_typical_min', 'screentime_7_wknd_min',
                                     'screentime_8_wknd_min', 'screentime_9_wknd_min','screentime_10_wknd_min', 'screentime_11_wknd_min','screentime_12_wknd_min', 'screentime_13_wknd_min',
                                     'screentime_14_wknd_min', 'screentime_1_wkdy_min','screentime_15_wknd_min', 'screentime_wknd_t_min', 'screentime_2_wkdy_min', 'screentime_3_wkdy_min', 'screentime_smq_sm_min', 'screen_14_wknd_min_y', 'screen_4_wkdy_min_y',
                                     'screen_wkdy_school_min_y', 'screen_9_wkdy_min_y','screen_3_wkdy_min_y', 'screen_wknd_school_min_y','screen_6_wkdy_min_y', 'screen_11_wknd_min_y', 'screen_1_wkdy2_min_y', 'screen_15_wknd_min_y', 'screen_9_wknd_min_y',
                                     'screen_wknd_typical_min_y', 'screen_5_wkdy_min_y', 'screen_8_wkdy_min_y', 'screen_12_wknd_min_y', 'screen_wkdy_typical_min_y', 'screen_10_wknd_min_y',
                                     'screentime_1_wkdy2_min', 'screentime_7_8_wknd_min','screentime_wkdy_school_min', 'screentime_wknd_school_min','screen_7_8_wknd_min_y']
for x in time_to_float:
    master_df[x] = master_df[x].fillna(0).astype('f')

In [57]:
#turn it all into minutes  
turn_me_into_minutes = ['screen1_wkdy_y', 'screen2_wkdy_y', 'screen3_wkdy_y', 'screen4_wkdy_y','screen5_wkdy_y', 'screen_wkdy_y', 'screen7_wknd_y', 'screen8_wknd_y',
                        'screen9_wknd_y', 'screen10_wknd_y', 'screen11_wknd_y','screen12_wknd_y', 'screentime_5_wkdy_hr', 'screentime_6_wkdy_hr', 'screentime_7_wkdy_hr', 'screentime_8_wkdy_hr', 
                                     'screentime_9_wkdy_hr','screentime_wkdy_typical_hr', 'screentime_7_wknd_hr','screentime_8_wknd_hr', 
                                     'screentime_9_wknd_hr', 'screentime_10_wknd_hr', 'screentime_1_wkdy_hr', 'screentime_11_wknd_hr',
                                     'screentime_12_wknd_hr', 'screentime_13_wknd_hr','screentime_14_wknd_hr', 'screentime_15_wknd_hr', 
                                     'screentime_wknd_typical_hr', 'screentime_2_wkdy_hr', 'screentime_3_wkdy_hr', 'screentime_smq_soc_med_hr',
                                     'screentime_4_wkdy_hr', 'screen_wknd_school_hr_y', 'screen_7_8_wknd_hr_y', 'screen_8_wkdy_hr_y', 
                                     'screen_14_wknd_hr_y', 'screen_wknd_typical_hr_y', 'screen_9_wknd_hr_y', 'screen_3_wkdy_hr_y', 
                                     'screen_4_wkdy_hr_y', 'screen_10_wknd_hr_y', 'screen_wkdy_typical_hr_y', 'screen_9_wkdy_hr_y', 
                                     'screen_wkdy_school_hr_y', 'screen_15_wknd_hr_y', 'screen_12_wknd_hr_y', 'screen_1_wkdy2_hr_y', 
                                     'screen_6_wkdy_hr_y', 'screen_5_wkdy_hr_y', 'screentime_1_wkdy2_hr', 'screentime_7_8_wknd_hr', 'screen_11_wknd_hr_y']
for x in turn_me_into_minutes:
    master_df[x] = (master_df[x])*60

In [58]:
master_df['screentime_weekday'] = master_df[['screen1_wkdy_y','screen2_wkdy_y','screen3_wkdy_y','screen4_wkdy_y','screen5_wkdy_y','screen_wkdy_y','screen_wkdy_typical_hr_y','screen_wkdy_typical_min_y']].sum(axis=1)
master_df['screentime_weekend'] = master_df[['screen7_wknd_y','screen8_wknd_y','screen9_wknd_y','screen10_wknd_y','screen11_wknd_y','screen12_wknd_y','screen_wknd_typical_hr_y','screen_wknd_typical_min_y']].sum(axis=1)
master_df['screentime_daily_average'] = ((master_df['screentime_weekday']*5) + (master_df['screentime_weekend']*2))/7
master_df['screentime_socialmedia'] = ((master_df[['screen5_wkdy_y','screentime_6_wkdy_hr','screentime_6_wkdy_min']].sum(axis=1))*5)+((master_df[['screen11_wknd_y','screentime_12_wknd_hr','screentime_12_wknd_min']].sum(axis=1))*2)/7
master_df['screentime_videogames']= (((master_df[['screen3_wkdy_y','screentime_3_wkdy_hr','screentime_3_wkdy_min','screen4_wkdy_y','screentime_4_wkdy_hr','screentime_4_wkdy_min']].sum(axis=1))*5)+
                                   ((master_df[['screen9_wknd_y','screentime_9_wknd_hr','screentime_9_wknd_min','screen10_wknd_y','screentime_10_wknd_hr','screentime_10_wknd_min']].sum(axis=1))*2))/7
master_df['screentime_tvmovies'] = ((master_df[['screen1_wkdy_y','screentime_1_wkdy_hr','screentime_1_wkdy_min']].sum(axis=1))*5)+((master_df[['screen7_wknd_y','screentime_7_wknd_hr','screentime_7_wknd_min']].sum(axis=1))*2)/7
master_df['screentime_videos'] = ((master_df[['screen2_wkdy_y','screentime_2_wkdy_hr','screentime_2_wkdy_min']].sum(axis=1))*5)+((master_df[['screen8_wknd_y','screentime_8_wknd_hr','screentime_8_wknd_min']].sum(axis=1))*2)/7
master_df['screentime_text'] = ((master_df[['screen4_wkdy_y','screentime_5_wkdy_hr','screentime_5_wkdy_min']].sum(axis=1))*5)+((master_df[['screen10_wknd_y','screentime_11_wknd_hr','screentime_11_wknd_min']].sum(axis=1))*2)/7
master_df['screentime_videocall'] = ((master_df[['screen_wkdy_y','screentime_8_wkdy_hr','screentime_8_wkdy_min']].sum(axis=1))*5)+((master_df[['screen12_wknd_y','screentime_14_wknd_hr','screentime_14_wknd_min']].sum(axis=1))*2)/7
#all screentime is in minutes
#videogame break down and browsing were removed because they were not available at each time point

In [59]:
master_df.head(10)

,subjectkey,src_subject_id,interview_date_x,interview_age_x,sex_x,eventname_x,screen1_wkdy_y,screen2_wkdy_y,screen3_wkdy_y,screen4_wkdy_y,...,prosocial_total,screentime_weekday,screentime_weekend,screentime_daily_average,screentime_socialmedia,screentime_videogames,screentime_tvmovies,screentime_videos,screentime_text,screentime_videocall
0,NDAR_INVKB30X083,NDAR_INVKB30X083,06/09/2019,133,F,1_year_follow_up_y_arm_1,120.0,60.0,60.0,15.0,...,27,285.0,30.0,212.142853,75.000000,57.857143,604.285706,300.000000,75.000000,75.000000
1,NDAR_INVUXBAPXMJ,NDAR_INVUXBAPXMJ,09/29/2018,121,F,1_year_follow_up_y_arm_1,30.0,180.0,0.0,15.0,...,31,240.0,330.0,265.714294,0.000000,27.857143,167.142853,951.428589,92.142853,83.571426
2,NDAR_INV82HYA45D,NDAR_INV82HYA45D,07/11/2018,129,M,1_year_follow_up_y_arm_1,15.0,120.0,180.0,30.0,...,29,345.0,480.0,383.571442,0.000000,222.857147,83.571426,651.428589,154.285721,4.285714
3,NDAR_INVCEWUA63Z,NDAR_INVCEWUA63Z,04/03/2019,141,F,1_year_follow_up_y_arm_1,120.0,240.0,0.0,240.0,...,35,870.0,810.0,852.857117,1268.571411,188.571426,668.571411,1268.571411,1217.142822,158.571426
4,NDAR_INVD3TWTXDB,NDAR_INVD3TWTXDB,12/02/2018,130,M,1_year_follow_up_y_arm_1,240.0,60.0,120.0,0.0,...,27,435.0,525.0,460.714294,0.000000,128.571426,1268.571411,334.285706,8.571428,79.285713
5,NDAR_INV6EU13388,NDAR_INV6EU13388,04/09/2019,140,F,1_year_follow_up_y_arm_1,30.0,0.0,60.0,30.0,...,31,180.0,240.0,197.142853,0.000000,107.142860,167.142853,0.000000,158.571426,308.571442
6,NDAR_INVNHKNUNA6,NDAR_INVNHKNUNA6,07/15/2019,130,M,1_year_follow_up_y_arm_1,0.0,15.0,60.0,0.0,...,31,75.0,180.0,105.000000,0.000000,77.142860,0.000000,92.142853,0.000000,0.000000
7,NDAR_INVCK8WM58K,NDAR_INVCK8WM58K,12/14/2018,123,M,1_year_follow_up_y_arm_1,15.0,240.0,240.0,15.0,...,26,510.0,495.0,505.714294,0.000000,250.714279,79.285713,1268.571411,75.000000,0.000000
8,NDAR_INVNVY8KZHN,NDAR_INVNVY8KZHN,08/31/2018,143,M,1_year_follow_up_y_arm_1,15.0,15.0,15.0,15.0,...,25,60.0,285.0,124.285713,4.285714,47.142857,92.142853,109.285713,83.571426,0.000000
9,NDAR_INVRHGBHZ4A,NDAR_INVRHGBHZ4A,07/09/2019,131,F,1_year_follow_up_y_arm_1,120.0,15.0,0.0,0.0,...,26,165.0,270.0,195.000000,167.142853,0.000000,651.428589,83.571426,0.000000,0.000000

In [60]:
os.getcwd()

'/srv/lab/fmri/abcd/beh'

In [61]:
#export to csv
master_df.to_csv('empathy_screentime_nca2022.csv')